name: Tự động Đóng gói & Triển khai Frontend

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: self-hosted # Đổi điểm nổ từ máy chủ GitHub sang chính server Ubuntu của bạn
    steps:
      - name: Kéo mã nguồn mới nhất
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt thư viện và Build dự án
        run: |
          npm install
          npm run build

      - name: Copy bản Build vào thư mục Nginx
        # Vì đang chạy ngay trên server, ta chỉ cần copy trực tiếp!
        run: sudo cp -r dist/* /var/www/demo-web/
